// Temas do Impostor — palavras concretas e conhecidas por todos (publico: livre | adulto).
window.CONTEUDO = window.CONTEUDO || {};
window.CONTEUDO.impostor = [
  { id: "lugares", tema: "Lugares", publico: "livre", palavras: ["Hospital", "Praia", "Aeroporto", "Escola", "Cinema", "Padaria", "Estádio", "Supermercado", "Igreja", "Zoológico", "Biblioteca", "Academia", "Farmácia", "Shopping", "Circo", "Fazenda", "Museu", "Restaurante", "Parque de diversões", "Posto de gasolina", "Delegacia", "Salão de beleza", "Piscina", "Banco", "Hotel", "Cemitério", "Feira", "Teatro", "Dentista", "Rodoviária"] },
  { id: "comidas", tema: "Comidas", publico: "livre", palavras: ["Pizza", "Hambúrguer", "Feijoada", "Sushi", "Lasanha", "Coxinha", "Pastel", "Brigadeiro", "Churrasco", "Pão de queijo", "Macarrão", "Tapioca", "Açaí", "Sorvete", "Pipoca", "Omelete", "Salada", "Pudim", "Cachorro-quente", "Esfiha", "Moqueca", "Panqueca", "Bolo de cenoura", "Strogonoff", "Batata frita", "Arroz com feijão", "Sopa", "Torrada", "Cuscuz", "Empada"] },
  { id: "animais", tema: "Animais", publico: "livre", palavras: ["Cachorro", "Gato", "Elefante", "Girafa", "Leão", "Macaco", "Cobra", "Tubarão", "Golfinho", "Pinguim", "Cavalo", "Vaca", "Galinha", "Coelho", "Tartaruga", "Jacaré", "Papagaio", "Coruja", "Abelha", "Formiga", "Borboleta", "Urso", "Panda", "Capivara", "Canguru", "Zebra", "Polvo", "Baleia", "Sapo", "Porco"] },
  { id: "profissoes", tema: "Profissões", publico: "livre", palavras: ["Médico", "Professor", "Bombeiro", "Policial", "Dentista", "Cozinheiro", "Piloto de avião", "Advogado", "Motorista de ônibus", "Cabeleireiro", "Pedreiro", "Eletricista", "Veterinário", "Jornalista", "Fotógrafo", "Garçom", "Enfermeiro", "Padeiro", "Astronauta", "Pescador", "Mecânico", "Palhaço", "Jogador de futebol", "Cantor", "Ator", "Carteiro", "Juiz", "Salva-vidas", "Programador", "Agricultor"] },
  { id: "objetos-casa", tema: "Objetos da casa", publico: "livre", palavras: ["Geladeira", "Sofá", "Televisão", "Travesseiro", "Espelho", "Chuveiro", "Fogão", "Micro-ondas", "Liquidificador", "Vassoura", "Ventilador", "Cama", "Mesa", "Cadeira", "Tapete", "Cortina", "Abajur", "Máquina de lavar", "Ferro de passar", "Toalha", "Escova de dentes", "Controle remoto", "Panela", "Guarda-roupa", "Relógio", "Lixeira", "Cafeteira", "Almofada", "Balde", "Tesoura"] },
  { id: "esportes", tema: "Esportes", publico: "livre", palavras: ["Futebol", "Vôlei", "Basquete", "Natação", "Tênis", "Surfe", "Skate", "Boxe", "Judô", "Ciclismo", "Corrida", "Golfe", "Handebol", "Xadrez", "Ginástica", "Capoeira", "Karatê", "Hipismo", "Esqui", "Fórmula 1", "Beisebol", "Rúgbi", "Tênis de mesa", "Escalada", "Remo", "Balé", "Boliche", "Sinuca", "Futevôlei", "Patinação"] },
  { id: "transporte", tema: "Meios de transporte", publico: "livre", palavras: ["Carro", "Ônibus", "Avião", "Bicicleta", "Moto", "Trem", "Metrô", "Navio", "Barco", "Helicóptero", "Caminhão", "Táxi", "Patinete", "Skate", "Balão", "Foguete", "Submarino", "Carroça", "Ambulância", "Trator", "Jet ski", "Teleférico", "Canoa", "Lancha", "Van", "Bonde", "Elevador", "Cavalo", "Patins", "Monociclo"] },
  { id: "instrumentos", tema: "Instrumentos musicais", publico: "livre", palavras: ["Violão", "Guitarra", "Piano", "Bateria", "Flauta", "Violino", "Saxofone", "Trompete", "Pandeiro", "Cavaquinho", "Sanfona", "Teclado", "Harpa", "Tambor", "Triângulo", "Gaita", "Contrabaixo", "Violoncelo", "Ukulele", "Berimbau", "Chocalho", "Xilofone", "Tamborim", "Cuíca", "Clarinete", "Trombone", "Banjo", "Surdo", "Agogô", "Órgão"] },
  { id: "roupas", tema: "Roupas e acessórios", publico: "livre", palavras: ["Camiseta", "Calça jeans", "Vestido", "Saia", "Bermuda", "Casaco", "Meia", "Tênis", "Chinelo", "Boné", "Chapéu", "Óculos", "Relógio", "Cinto", "Gravata", "Pijama", "Biquíni", "Sunga", "Luva", "Cachecol", "Bolsa", "Mochila", "Brinco", "Colar", "Anel", "Pulseira", "Bota", "Sandália", "Terno", "Capa de chuva"] },
  { id: "frutas", tema: "Frutas", publico: "livre", palavras: ["Banana", "Maçã", "Laranja", "Uva", "Morango", "Abacaxi", "Melancia", "Manga", "Mamão", "Limão", "Pera", "Kiwi", "Coco", "Goiaba", "Maracujá", "Caju", "Jabuticaba", "Pêssego", "Cereja", "Melão", "Abacate", "Tangerina", "Acerola", "Framboesa", "Figo", "Ameixa", "Pitanga", "Graviola", "Carambola", "Açaí"] },
  { id: "corpo", tema: "Partes do corpo", publico: "livre", palavras: ["Nariz", "Orelha", "Olho", "Boca", "Dente", "Língua", "Cabelo", "Mão", "Pé", "Joelho", "Cotovelo", "Ombro", "Barriga", "Umbigo", "Costas", "Pescoço", "Dedo", "Unha", "Sobrancelha", "Bochecha", "Queixo", "Testa", "Tornozelo", "Calcanhar", "Coração", "Pulmão", "Cérebro", "Estômago", "Osso", "Bigode"] },
  { id: "brinquedos", tema: "Brinquedos e brincadeiras", publico: "livre", palavras: ["Boneca", "Bola", "Pipa", "Pião", "Ioiô", "Carrinho", "Quebra-cabeça", "Lego", "Videogame", "Esconde-esconde", "Pega-pega", "Amarelinha", "Pular corda", "Bambolê", "Dominó", "Baralho", "Dama", "Xadrez", "Bolinha de gude", "Escorregador", "Balanço", "Gangorra", "Cama elástica", "Massinha", "Ursinho de pelúcia", "Patinete", "Estilingue", "Cabo de guerra", "Batata quente", "Stop"] },
  { id: "festas", tema: "Festas e datas", publico: "livre", palavras: ["Natal", "Ano Novo", "Carnaval", "Páscoa", "Festa junina", "Aniversário", "Casamento", "Halloween", "Dia das Mães", "Dia dos Pais", "Dia das Crianças", "Formatura", "Chá de bebê", "Réveillon na praia", "Batizado", "Festa do pijama", "Churrasco de domingo", "Copa do Mundo", "Dia dos Namorados", "Festa surpresa", "Bodas de ouro", "Chá de panela", "Festa à fantasia", "Show de rock", "Micareta", "Oktoberfest", "Bumba meu boi", "Parintins", "Festa de 15 anos", "Amigo secreto"] },
  { id: "natureza", tema: "Natureza", publico: "livre", palavras: ["Montanha", "Vulcão", "Cachoeira", "Rio", "Lago", "Oceano", "Floresta", "Deserto", "Ilha", "Caverna", "Arco-íris", "Tempestade", "Raio", "Neve", "Terremoto", "Tornado", "Pôr do sol", "Lua cheia", "Estrela cadente", "Eclipse", "Geleira", "Pântano", "Duna", "Recife de coral", "Árvore", "Flor", "Cacto", "Cogumelo", "Onda", "Nuvem"] },
  { id: "cozinha", tema: "Utensílios de cozinha", publico: "livre", palavras: ["Garfo", "Faca", "Colher", "Prato", "Copo", "Panela de pressão", "Frigideira", "Chaleira", "Concha", "Espátula", "Ralador", "Peneira", "Escorredor", "Tábua de carne", "Rolo de massa", "Batedeira", "Torradeira", "Forma de bolo", "Abridor de latas", "Saca-rolhas", "Liquidificador", "Xícara", "Jarra", "Bandeja", "Pegador", "Pilão", "Assadeira", "Pote", "Garrafa térmica", "Avental"] },
  { id: "super-herois", tema: "Heróis e personagens", publico: "livre", palavras: ["Batman", "Super-Homem", "Homem-Aranha", "Mulher-Maravilha", "Hulk", "Homem de Ferro", "Capitão América", "Thor", "Shrek", "Mickey", "Bob Esponja", "Harry Potter", "Pikachu", "Mario", "Chaves", "Mônica", "Cebolinha", "Saci-Pererê", "Branca de Neve", "Cinderela", "Pinóquio", "Peter Pan", "Papai Noel", "Elsa", "Simba", "Woody", "Buzz Lightyear", "Scooby-Doo", "Pica-Pau", "Coringa"] },
  { id: "escola", tema: "Coisas da escola", publico: "livre", palavras: ["Lápis", "Caneta", "Borracha", "Caderno", "Mochila", "Estojo", "Régua", "Apontador", "Lousa", "Giz", "Recreio", "Merenda", "Prova", "Boletim", "Diretor", "Professora", "Uniforme", "Cantina", "Quadra", "Biblioteca", "Tesoura sem ponta", "Cola", "Mapa", "Globo terrestre", "Calculadora", "Dicionário", "Excursão", "Lição de casa", "Chamada", "Carteira"] },
  { id: "tecnologia", tema: "Tecnologia", publico: "livre", palavras: ["Celular", "Computador", "Notebook", "Tablet", "Fone de ouvido", "Mouse", "Teclado", "Impressora", "Wi-Fi", "Carregador", "Pen drive", "Câmera", "Drone", "Robô", "Videogame", "Smartwatch", "Televisão", "Caixa de som", "Controle remoto", "GPS", "Aplicativo", "Senha", "Selfie", "Emoji", "Rede social", "Microfone", "Pilha", "Webcam", "Satélite", "Inteligência artificial"] },
  { id: "bebidas", tema: "Bebidas", publico: "livre", palavras: ["Café", "Chá", "Suco de laranja", "Refrigerante", "Água de coco", "Leite", "Chocolate quente", "Limonada", "Milkshake", "Vitamina de banana", "Água com gás", "Chimarrão", "Tereré", "Guaraná", "Caldo de cana", "Iogurte", "Achocolatado", "Capuccino", "Suco de uva", "Mate gelado", "Isotônico", "Energético", "Leite condensado", "Caldo verde", "Sopa", "Groselha", "Café com leite", "Suco verde", "Smoothie", "Água"] },
  { id: "adulto-bar", tema: "No bar", publico: "adulto", palavras: ["Cerveja", "Caipirinha", "Vinho", "Whisky", "Tequila", "Vodka", "Cachaça", "Gin tônica", "Espumante", "Chope", "Petisco", "Porção de fritas", "Garçom", "Conta", "Brinde", "Ressaca", "Karaokê", "Happy hour", "Sinuca", "Balcão", "Gelo", "Limão", "Saideira", "Dose", "Drink", "Taça", "Caneca", "Amendoim", "Torresmo", "Batida"] },
];
